// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongTro.Data;

#nullable disable

namespace QuanLyPhongTro.src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122065438_AddBillDateCreated")]
    partial class AddBillDateCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongTro.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("IdPerson")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_Bill");

                    b.HasIndex("IdPerson");

                    b.HasIndex("IdRoom");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.BillDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Electricity")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdService")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("Water")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK_BillDetail");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdService");

                    b.ToTable("BillDetail");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DesiredDurationMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("DesiredStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdRenter");

                    b.HasIndex("IdRoom");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<decimal?>("Deposit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdRenter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Contract");

                    b.HasIndex("IdRenter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateIncurred")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdOwner");

                    b.HasIndex("IdRoom");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.FavoriteRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_FavoriteRoom");

                    b.HasIndex("RoomId");

                    b.HasIndex("PersonId", "RoomId")
                        .IsUnique()
                        .HasFilter("[PersonId] IS NOT NULL");

                    b.ToTable("FavoriteRoom");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Notice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Idreport")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDReport");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Notice");

                    b.HasIndex("Idreport")
                        .IsUnique()
                        .HasFilter("[IDReport] IS NOT NULL");

                    b.ToTable("Notice");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Payment", b =>
                {
                    b.Property<Guid>("IdBill")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBill")
                        .HasName("PK_Payment");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdDetail")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Person");

                    b.HasIndex("IdDetail");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.PersonDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CCCD");

                    b.Property<byte[]>("CccdImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Gmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK_PersonDetail");

                    b.ToTable("PersonDetail");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdReporter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Report");

                    b.HasIndex("IdReporter");

                    b.HasIndex("IdRoom");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Area")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("IdOwner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Room");

                    b.HasIndex("IdOwner");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.RoomImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid?>("IdRoom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_RoomImage");

                    b.HasIndex("IdRoom");

                    b.ToTable("RoomImage");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PricePerUnit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Service");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Bill", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "IdPersonNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdPerson")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Bill_Person");

                    b.HasOne("QuanLyPhongTro.Models.Room", "IdRoomNavigation")
                        .WithMany("Bills")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Bill_Room");

                    b.Navigation("IdPersonNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.BillDetail", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Bill", "IdBillNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdBill")
                        .HasConstraintName("FK_BillDetail_Bill");

                    b.HasOne("QuanLyPhongTro.Models.Service", "IdServiceNavigation")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdService")
                        .HasConstraintName("FK_BillDetail_Service");

                    b.Navigation("IdBillNavigation");

                    b.Navigation("IdServiceNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.BookingRequest", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "Renter")
                        .WithMany()
                        .HasForeignKey("IdRenter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongTro.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Contract", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "IdRenterNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Contract_Renter");

                    b.HasOne("QuanLyPhongTro.Models.Room", "IdRoomNavigation")
                        .WithMany("Contracts")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Contract_Room");

                    b.Navigation("IdRenterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Expense", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "Owner")
                        .WithMany()
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyPhongTro.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("IdRoom");

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.FavoriteRoom", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("QuanLyPhongTro.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Notice", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Report", "IdreportNavigation")
                        .WithOne("Notice")
                        .HasForeignKey("QuanLyPhongTro.Models.Notice", "Idreport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notice_Report");

                    b.Navigation("IdreportNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Payment", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Bill", "IdPaymentNavigation")
                        .WithOne("Payment")
                        .HasForeignKey("QuanLyPhongTro.Models.Payment", "IdBill")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Bill");

                    b.Navigation("IdPaymentNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Person", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.PersonDetail", "IdDetailNavigation")
                        .WithMany("People")
                        .HasForeignKey("IdDetail")
                        .HasConstraintName("FK_Person_PersonDetail");

                    b.Navigation("IdDetailNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Report", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "IdReporterNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdReporter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Report_Reporter");

                    b.HasOne("QuanLyPhongTro.Models.Room", "IdRoomNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("IdRoom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Report_Room");

                    b.Navigation("IdReporterNavigation");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Room", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Person", "IdOwnerNavigation")
                        .WithMany("Rooms")
                        .HasForeignKey("IdOwner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Room_Owner");

                    b.Navigation("IdOwnerNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.RoomImage", b =>
                {
                    b.HasOne("QuanLyPhongTro.Models.Room", "IdRoomNavigation")
                        .WithMany("RoomImages")
                        .HasForeignKey("IdRoom")
                        .HasConstraintName("FK_RoomImage_Room");

                    b.Navigation("IdRoomNavigation");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Bill", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Person", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Contracts");

                    b.Navigation("Reports");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.PersonDetail", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Report", b =>
                {
                    b.Navigation("Notice");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Room", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Contracts");

                    b.Navigation("Reports");

                    b.Navigation("RoomImages");
                });

            modelBuilder.Entity("QuanLyPhongTro.Models.Service", b =>
                {
                    b.Navigation("BillDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
